Repository Ornithopter-pilot/interview-coder-withoupaywall-opensource, pull requests merged in 2025-04, with the labels that each got.

#46 Fix default complexity issue and upgraded critical dependency
  package.json
  src/_pages/Solutions.tsx
Labels: bug, enhancement

#36 Integrate Claude AI
  electron/ConfigHelper.ts
  electron/ProcessingHelper.ts
  package.json
  src/components/Settings/SettingsDialog.tsx
Labels: enhancement

#41 Replace dialog boxes with in-app notifications for missing screenshots
  electron/ProcessingHelper.ts
Labels: duplicate, enhancement

#61 Fix URL check
  electron/main.ts
Labels: bug, Need review
